### ISSUE TITLE
Pull requests here won’t count toward Hacktoberfest.

### ISSUE THREAD

**Issue by hacktoberfest-team** [Ishaan28malik/HACKTOBERFEST2019#246]
Hi there,

Thanks for your interest in Hacktoberfest and helping others learn how to make their first contributions to open source!

That said, high-quality contributions are part of the [the core values of Hacktoberfest](https://hacktoberfest.digitalocean.com/details), so we kindly ask that you do not create repositories which allow users to quickly gain a PR toward completing the challenge.

We encourage you to take a look at our list of [Hacktoberfest issues](https://hacktoberfest.digitalocean.com/#projects) for inspiration and ideas about making meaningful contributions to open source projects.

_Due to this, we've added this repository to our list of excluded repositories and pull requests here will not count toward Hacktoberfest 2019._

Please note, you are welcome to keep running this repository as a learning tool for new contributors to open-source, but pull requests won’t count toward Hacktoberfest.

Happy Hacking,
The Hacktoberfest Team

Hacktoberfest is presented by [DigitalOcean](https://do.co/hacktoberfest50) and [DEV](https://dev.to).

**Comment by jelenagiovanni** [comment]
That's definetely bad news :( I think that due to the previous announcement the best and most honest thing to do right now is to remove / delete the repo so that it is not misleading with all the future contributors looking for their valid Hacktoberfest 2019 RPs. 

I really appreciate the effort of @Ishaan28malik and his invest in documenting and creating this repo but in order to avoid useless issues with the Hacktoberfest Team decission and all the contributors that have been affected by marking their prs as spam, the best is to remove it and contribute in the rest of great @Ishaan28malik projects.

**Comment by Ishaan28malik** [comment]
Ok thanks for the update I really appreciate that Hacktoberfest has taken this step and surely will be conveying this to the community aswell.

@hacktoberfest-team
